server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100
logging:
  level:
    cc.carce.sale: debug
    org.springframework: warn
spring:
  messages:
    basename: i18n/messages
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  devtools:
    restart:
      enabled: false
  datasource:
    initialSize: 5
    minIdle: 10
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    maxEvictableIdleTimeMillis: 900000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    webStatFilter:
      enabled: true
    statViewServlet:
      enabled: true
      allow: null
      url-pattern: /druid/*
      login-username: ruoyi
      login-password: 123456
    filter:
      stat:
        enabled: true
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      wall:
        config:
          multi-statement-allow: true

  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    expose-spring-macro-helpers: true
  # redis:
  #   host: localhost
  #   port: 6379
  #   database: 0
  #   password: null
  #   timeout: 10s
  #   lettuce:
  #     pool:
  #       min-idle: 0
  #       max-idle: 8
  #       max-active: 8
  #       max-wait: -1ms
mybatis:
  typeAliasesPackage: cc.carce.sale.entity
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml
  
ecpay:
  service-url: https://payment-stage.ecpay.com.tw/Cashier/AioCheckOut/V5
  return-url: https://www.weisliu.com/ecpay/return          # ✅ 支付結果回調
  store-callback-url: https://www.weisliu.com/shipping/storeCallback  # ✅ 超商門市回調
  client-back-url: https://www.weisliu.com/checkout/success
  map-url: https://logistics-stage.ecpay.com.tw/Express/map   # ✅ 新增物流門市地圖 API
  hash-key: 1g0h0vxYukFihTZX
  hash-iv: pW1pnfGdkQYuKbBQ
  merchant-id: 3014517
  logistics-url: https://logistics-stage.ecpay.com.tw   # 🔹 測試物流 API


