carce:
  prefix: https://testcloud.carce.cc
  webUrl: https://sale.carce.cc
  ftp:
    server: testcloud.carce.cc
    port: 21
    user: testcloud
    password: x32*9oFb6
ruoyi:
  profile: /root/files
spring:
  datasource:
    carcecloud:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/test_carce_cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: test_cloud
      password: "oP9m7_2h"
    manager:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/carbuy_cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: carbuy_cloud
      password: "L2k~5HR?v9wewdgl"

# 绿界支付配置
ecpay:
  # 测试环境配置
  production: false
  merchant-id: "3002607"  # 官方测试商户编号
  hash-key: "pwFHCqoQZGmho4w6"  # 官方测试HashKey
  hash-iv: "EkRm7iFT261dpevs"   # 官方测试HashIV
  return-url: "https://carce.yanjiashuo.cn/ecpay/return"
  notify-url: "https://carce.yanjiashuo.cn/ecpay/callback"
  client-back-url: "https://carce.yanjiashuo.cn/my-order/detail-page?orderId="
  result-url: "https://carce.yanjiashuo.cn/ecpay/result"
  # 查询API地址配置
  query-server-url: "https://payment-stage.ecpay.com.tw/Cashier/QueryTradeInfo/V5"
