carce:
  prefix: https://testcloud.carce.cc
  webUrl: https://sale.carce.cc
  ftp:
    server: 125.227.138.209
    port: 21
    user: testcloud
    password: x32*9oFb6
ruoyi:
  profile: /root/files
spring:
  datasource:
    carcecloud:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:4416/car?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: "Wbf6XkTS3h55MC88eSRr"
    manager:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:4416/ry?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: "Wbf6XkTS3h55MC88eSRr"
